### ISSUE TITLE
feature: FixedWindow padding

### ISSUE THREAD

**Issue by levic** [python-bonobo/bonobo#269]
Use case:

Sometimes I have data that is significantly faster to handle in bulk. An example would be writing a series of records back to a database can be much faster if done 100 or 1000 at a time in a single transaction (esp with a database like sqlite that locks a table for writes)

`FixedWindow` already allows you to do this but `FixedWindow` always pads the data with `None`

It would be more convenient if `FixedWindow` could be configured to suppress the padding

**Comment by levic** [comment]
From a separation of concerns perspective it would be even better if this could be a decorator to a transform function since it seems to me to be an implementation detail of the transform function and not something the code assembling the pipeline should have to know about

eg something like:

```python
@fixed_window(100)
@service('db')
def write_to_database(*items, db):
    with db.transaction():
        for item in items:
            db.write_row(item)
```

I tried but getting this to work in a decorator was more complicated than I initially thought (esp with the introspection of transform function arguments I'm not sure how you can easily construct a decorator to do this)

**Comment by hartym** [comment]
Thanks, will look at this in a few days.

First thought about decorator : not sure about that, as it makes things harder to test in isolation imho. But we need a way to have "children nodes" at some point, so it would make sense that a Window node delegates to a Foo node. I'll think about it more extensively when I find some time.

**Comment by hartym** [comment]
There is something I don't understand here.

If you "do not pad", then the io-shape may change, and that usually makes bonobo to complain (like, throw an unrecoverrable).

How does this work for you?

**Comment by levic** [comment]
> the io-shape may change, and that usually makes bonobo to complain

Ah I have encountered this now -- the unit tests only test the `Configurable` but the error is raised by the `NodeExecutionContext` and in my local app everything fit inside one window (size=10,000) so I hadn't noticed. I guess this isn't really going to work.

**Comment by levic** [comment]
Incidentally, if you ever refactor Bonobo the one thing that I've had issues with is too much 'magic' (eg automatically treating transforms with a signature of `def myfunc(*items)` differently to `def myfunc(item)`, automatically unwrapping lists of items in a Configurable when I want the item itself being transformed to be a list).

It would be less confusing if there was a single supported interface (eg always pass a list of items to a transform function. If someone wants to process items one at a time then there can be a decorator to iterate over the list of items and pass them into the function). It's slightly less convenient, but stops bonobo guessing the wrong thing.

**Comment by hartym** [comment]
So first, your usage FixedWindow is quite edge case, I understand you're using it to "buffer" everything. I need to have a look on that, never thought someone would use it this way.

Second, your comment is very interesting because in fact, Bonobo does not try to "guess" anything. It always use the same rules to pass data to a function. The main problem you're highlighting here is that those rules are not well documented, and I 200% agree on that. I don't think functions with a (*args) signature are treated differently than functions with (arg0) signature, but the latest does not work with more than one argument, of course.

When I say "io-shape change", I mean that bonobo strongly refuses to have nodes with input signature changing from one call to another, and this is important for a lot of use cases. Yes it can be valid to have a function called with 3, then 2, then 3 arguments, but bonobo refuses that because quite often, it means that the previous node forgot an arg in the middle, shifting everything to the left. Which is never good. The only "magic" bonobo does in this regard is some signature introspection to raise errors, but the calls always obey the same rules.

Of course, I also 100% agree with you that whatever makes it less magic is good. We still need to keep in mind that it should be useable with basically any user defined function, and I donc want users to change their function signatures to make it fit "the bonobo way". This is probably the #1 reason why it's working that way, now.

**Comment by hartym** [comment]
FixedWindow should stay "Fixed". This use case of buffering everything before handling it is basically saying you wanna get rid of streaming while streaming data, which does not really make sense.

Let us know if we overlooked something, closing meanwhile.
