### ISSUE TITLE
Format() does not respect the order of new fields

### ISSUE THREAD

**Issue by Ooxie** [python-bonobo/bonobo#286]
Bonobo version: 0.6.2 + #282
Python version: 3.5.2
Platform: Linux 4.15.0-30 - Ubuntu 16.04.5

Given the input file 'input.csv':
```
x
aaa
```

And this minimal code (using a custom printer function instead of PrettyPrinter or CsvWriter, so as to isolate the issue), where two fields are added to the schema through the use of the Format function:
```python
#!/usr/bin/env python
# -*- coding: utf_8 -*-

import bonobo


@bonobo.config.use_raw_input
def printer(row):
    print(row)


def get_graph():
    graph = bonobo.Graph()
    graph.add_chain(
        bonobo.CsvReader(path='input.csv'),
        bonobo.Format(
            y='',
            z='',
        ),
        printer,
    )
    return graph


if __name__ == '__main__':
    bonobo.run(get_graph())
```

The output is either of the two lines below, in a supposedly random fashion:
```
Bag(x='aaa', y='', z='')
```
```
Bag(x='aaa', z='', y='')
```

Whatever the number of fields (initial and additional), the initial fields are always kept on the left in the correct order, and the additional fields are always on the right but in a random order.

The order of the additional fields should be respected everytime.

**Comment by hartym** [comment]
On one side, this is not what we may expect.

On another side, dicts (and kwargs, implemented as dicts) does not keep insertion order in python 3.5, and there's very little we can do about that.

Not sure if we should (or even can) do anything about this, the only thing I can think of is to have an alternate implementation that does not use kwargs for that, but some kind of list / iterable / ... to provide the list of things to format.

**Comment by KPilnacek** [comment]
Hello @Ooxie,

in `bonobo.Format` the keyword arguments are captured using the `**` syntax resulting in a `dict`. The problem is that in [Python 3.5 and below the order of keys in a dict was not preserved](https://stackoverflow.com/a/39980744).

To overcome this, you can either upgrade your Python version (to 3.6, where the order is unofficially kept, or to 3.7+, where the order is officially supported); or use `bonobo.OrderFields(('x', 'y', 'z')),` to enforce the order of fields you require.

With regards
Krystof
